// Public compatibility facade. Source implementations live in ./google.
export type { DateRangeData } from './google/types';
export type { Ga4ExtendedData } from './google/types';
export { getGoogleSheetData } from './google/sheets';
export { getSearchConsoleData } from './google/gsc';
export { GOOGLE_GENAI_DATA_VERSION } from './google/gsc';
export { getGoogleGenAiPerformanceData } from './google/gsc';
export { getTopQueries } from './google/gsc';
export { getAnalyticsData } from './google/ga4';
export { getPaidSearchData } from './google/ga4';
export { getAiTrafficData } from './google/ga4';
export { getGa4DimensionReport } from './google/ga4';
export type { ConvertingPageData } from './google/ga4';
export { getTopConvertingPages } from './google/ga4';
export { getLandingPageMetricsForPaths } from './google/ga4';
export type { GscPageData } from './google/gsc';
export { getGscDataForPagesWithComparison } from './google/gsc';
export { getGscPageCtr } from './google/gsc';
export type { LandingPageQueries } from './google/gsc';
export { getQueriesByLandingPageObject } from './google/gsc';
export type { FollowUpPath } from './google/ga4';
export type { LandingPageFollowUpData } from './google/ga4';
export { getLandingPageFollowUpPaths } from './google/ga4';
export type { GoogleAdsRow } from './google/ads';
export type { GoogleAdsData } from './google/ads';
export { getGoogleAdsReport } from './google/ads';
export { getGoogleAdsFromSheet } from './google/ads';
export type { PromptTrackingResult, PromptQueryData } from './google/gsc';
export { DEFAULT_PROMPT_TRACKING_MIN_WORDS } from './google/gsc';
export { getPromptLikeQueries } from './google/gsc';
